
SET search_path TO lyfter_car_rental;

-- SCHEMA:
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL,
    date_of_birth DATE NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('active', 'deactivated', 'payment pending'))
);

CREATE TABLE cars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(15) NOT NULL,
    model VARCHAR(15) NOT NULL,
    year SMALLINT NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('available', 'rental ongoing', 'rent ineligible'))
);

CREATE TABLE rentals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INTEGER REFERENCES cars(id),
    user_id INTEGER REFERENCES users(id),
    rental_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(30) NOT NULL CHECK (status IN ('ongoing', 'returned'))
);

-- USERS DATA:
insert into users (id, full_name, email, username, password, date_of_birth, status) values (1, 'Lavina Seares', 'lseares0@npr.org', 'lseares0', 'oB7!(3QcL22wCWgz', '3/28/1990', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (2, 'Livvie De Carlo', 'lde1@woothemes.com', 'lde1', 'xU7|G7FtWpar', '12/15/1945', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (3, 'Rosanna Gibson', 'rgibson2@fema.gov', 'rgibson2', 'xI5??m/B/krxaqC', '12/16/1973', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (4, 'Cyndia Comsty', 'ccomsty3@list-manage.com', 'ccomsty3', 'cX8<*dGu2!Cb', '6/30/1986', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (5, 'Camille Cuerdall', 'ccuerdall4@icq.com', 'ccuerdall4', 'nH6=0NbT(G5.{', '4/3/1967', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (6, 'Mignon Isaak', 'misaak5@mozilla.com', 'misaak5', 'wT7/7RRTP', '9/15/1969', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (7, 'Zaneta Glendining', 'zglendining6@upenn.edu', 'zglendining6', 'xN6<<CW_&', '9/22/1950', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (8, 'Candis Fellon', 'cfellon7@patch.com', 'cfellon7', 'kY2.KZ.`UXjQxy,5', '5/23/1981', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (9, 'Jemima Camerello', 'jcamerello8@imgur.com', 'jcamerello8', 'rA3~7JI7', '1/10/1979', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (10, 'Seline Glencros', 'sglencros9@xinhuanet.com', 'sglencros9', 'wB7=W''Nyf~.', '5/1/1941', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (11, 'Kayne Eccersley', 'keccersleya@marriott.com', 'keccersleya', 'jP2=*GU|8', '1/30/1987', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (12, 'Hamlen Kuban', 'hkubanb@msn.com', 'hkubanb', 'bB8~uPR"riA~={qT', '5/21/1998', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (13, 'Lorie Coleford', 'lcolefordc@si.edu', 'lcolefordc', 'eX8+fk$iIO', '9/24/1995', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (14, 'Iolande Crook', 'icrookd@ted.com', 'icrookd', 'uG2>ao~g}4t', '3/20/1967', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (15, 'Ximenes Coumbe', 'xcoumbee@booking.com', 'xcoumbee', 'fC7?C|~<C`b\k', '5/15/1955', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (16, 'Lizbeth Worboy', 'lworboyf@amazon.co.jp', 'lworboyf', 'eW7,hA`ic0Ml', '3/9/1960', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (17, 'Berna Simoncelli', 'bsimoncellig@cargocollective.com', 'bsimoncellig', 'pE0$bY1(ma1hp<N', '6/21/1966', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (18, 'Marabel Nund', 'mnundh@freewebs.com', 'mnundh', 'oV7<@VWf=<8SQ0H', '9/19/1935', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (19, 'Patin Woolfitt', 'pwoolfitti@japanpost.jp', 'pwoolfitti', 'iX8>GFR''&uS', '7/2/1959', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (20, 'Katuscha Boich', 'kboichj@ocn.ne.jp', 'kboichj', 'lF8=I4U>N)S=E\l', '10/28/1971', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (21, 'Berri Gronou', 'bgronouk@nature.com', 'bgronouk', 'bL5=<UW</HTH/#Mm', '11/2/1967', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (22, 'Bertie Sturges', 'bsturgesl@vinaora.com', 'bsturgesl', 'nW0@%*''H3{', '8/7/1952', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (23, 'Steven Taylorson', 'staylorsonm@spiegel.de', 'staylorsonm', 'hC7(K62=Hy5=A', '8/13/1957', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (24, 'Jobina Godbert', 'jgodbertn@people.com.cn', 'jgodbertn', 'cH0)Ya/(adQs5AN', '12/16/2002', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (25, 'Nickola Testro', 'ntestroo@sciencedaily.com', 'ntestroo', 'mZ9"%Ozo', '3/10/1995', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (26, 'Corby Catteroll', 'ccatterollp@psu.edu', 'ccatterollp', 'lZ3_''Y+#xHW9&&K', '7/10/1968', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (27, 'Cecilia Sperling', 'csperlingq@meetup.com', 'csperlingq', 'xI1{k\?145c', '12/2/1965', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (28, 'Marthena Jeffels', 'mjeffelsr@springer.com', 'mjeffelsr', 'bP7&PzNJ6me', '7/1/1982', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (29, 'Brandise Clowton', 'bclowtons@washington.edu', 'bclowtons', 'tC1`5\.?&O_=t', '1/23/1953', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (30, 'Maudie Spiniello', 'mspiniellot@washington.edu', 'mspiniellot', 'nN4/B&=z/zOtr', '9/4/1967', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (31, 'Townie Bearsmore', 'tbearsmoreu@smugmug.com', 'tbearsmoreu', 'tJ9)V/t_', '9/7/1941', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (32, 'Agnesse Bispham', 'abisphamv@dailymotion.com', 'abisphamv', 'cE4~EVqvE5Ass+k', '8/9/1974', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (33, 'Fowler Hanmer', 'fhanmerw@youtu.be', 'fhanmerw', 'uD5.TX3''S8hGXH', '9/23/2001', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (34, 'Alysia Pilmore', 'apilmorex@goodreads.com', 'apilmorex', 'yM4%O<k=Uv+$no\o', '4/4/1964', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (35, 'Elizabeth Shemmin', 'eshemminy@illinois.edu', 'eshemminy', 'bI4_e?%n#', '2/12/1980', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (36, 'Yorke Gillett', 'ygillettz@de.vu', 'ygillettz', 'sI9$yzs|f15w@', '5/24/1959', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (37, 'Kristina McIlroy', 'kmcilroy10@angelfire.com', 'kmcilroy10', 'kL8*6o/Vf', '4/24/1970', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (38, 'Louisette Wiltshaw', 'lwiltshaw11@yelp.com', 'lwiltshaw11', 'bL1`hvF*hl,r', '5/19/1951', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (39, 'Curran Houseman', 'chouseman12@people.com.cn', 'chouseman12', 'lX0<#=E1AMKI', '10/14/1945', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (40, 'Teddie Deller', 'tdeller13@yellowpages.com', 'tdeller13', 'zA7%COIa10', '3/25/1981', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (41, 'Pandora Witter', 'pwitter14@theglobeandmail.com', 'pwitter14', 'sB2|r0=Yd', '6/1/1945', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (42, 'Kendricks Lumox', 'klumox15@hibu.com', 'klumox15', 'vF6$!!g9FSx0zo', '11/22/1995', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (43, 'Jarvis Tillyer', 'jtillyer16@tuttocitta.it', 'jtillyer16', 'tI1~%&anVvGl_i>b', '11/11/1999', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (44, 'Sibyl Toppin', 'stoppin17@usgs.gov', 'stoppin17', 'lX7.SAS{M#', '1/5/1939', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (45, 'Bendick Halsey', 'bhalsey18@nature.com', 'bhalsey18', 'fC2>e_P9XSxD', '6/25/1954', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (46, 'Xylina Juggings', 'xjuggings19@nymag.com', 'xjuggings19', 'pW4\KFlPZBp1', '5/3/1948', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (47, 'Claresta Winckworth', 'cwinckworth1a@infoseek.co.jp', 'cwinckworth1a', 'hO5&dj~}*GJVMG', '8/27/1959', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (48, 'Fedora Reding', 'freding1b@furl.net', 'freding1b', 'jQ2<l~bp>ktAp', '7/20/1940', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (49, 'Muriel Catlin', 'mcatlin1c@state.tx.us', 'mcatlin1c', 'rV0,r0AoyP&\d', '6/27/1995', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (50, 'Morse Rosander', 'mrosander1d@auda.org.au', 'mrosander1d', 'kM6{rb/j@', '4/11/1980', 'active');