SET search_path TO lyfter_car_rental;

-- SCHEMA:
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL,
    date_of_birth DATE NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('active', 'deactivated', 'payment pending'))
);

CREATE TABLE cars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate CHAR(6) UNIQUE NOT NULL,
    brand VARCHAR(15) NOT NULL,
    model VARCHAR(15) NOT NULL,
    year SMALLINT NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('available', 'rental ongoing', 'rent ineligible'))
);

CREATE TABLE rentals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INTEGER REFERENCES cars(id),
    user_id INTEGER REFERENCES users(id),
    rental_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(30) NOT NULL CHECK (status IN ('ongoing', 'returned')),
    return_date DATE
);

-- USERS DATA:
insert into users (id, full_name, email, username, password, date_of_birth, status) values (1, 'Samaria Peto', 'speto0@slashdot.org', 'speto0', 'lE0+5l"\*B', '1963-08-05', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (2, 'Maybelle Fitch', 'mfitch1@comcast.net', 'mfitch1', 'gS5!U2RQ', '1935-09-05', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (3, 'Dionisio Cramond', 'dcramond2@admin.ch', 'dcramond2', 'hN6#''wHNoam<', '1979-12-16', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (4, 'Pammie Gaskell', 'pgaskell3@sakura.ne.jp', 'pgaskell3', 'qT4$!B1`T}', '1956-12-15', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (5, 'Ivett Sinkin', 'isinkin4@parallels.com', 'isinkin4', 'sU9)#ba{', '1954-02-10', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (6, 'Carly Mignot', 'cmignot5@vinaora.com', 'cmignot5', 'cC6?F_ga&''!fZF(', '1947-02-06', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (7, 'Mead Kibel', 'mkibel6@columbia.edu', 'mkibel6', 'aN1?.`Zh"#+kO`', '1974-10-16', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (8, 'Arabel Arkow', 'aarkow7@icq.com', 'aarkow7', 'nR9''9i,%%9=9(A8=', '1966-07-10', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (9, 'Reggis Dark', 'rdark8@jalbum.net', 'rdark8', 'dE3%VTye9.', '1993-11-12', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (10, 'Rube O''Luney', 'roluney9@shinystat.com', 'roluney9', 'xE9=d}Lc/8yh$evN', '1951-09-08', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (11, 'Trina Sloyan', 'tsloyana@nps.gov', 'tsloyana', 'iN5|_/FFX\`gI', '1956-08-08', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (12, 'Hilliary Powlett', 'hpowlettb@usgs.gov', 'hpowlettb', 'bR1!(51+s1_', '1945-10-29', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (13, 'Sheree Ruddiman', 'sruddimanc@bing.com', 'sruddimanc', 'mK2+)aWf@)&/', '1988-07-28', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (14, 'Jessa Candish', 'jcandishd@issuu.com', 'jcandishd', 'eH9%?(ABzmz', '1956-10-31', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (15, 'Maribelle Myring', 'mmyringe@flavors.me', 'mmyringe', 'xF2\Du@_h_J<y', '1955-02-13', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (16, 'Rahel McWhirter', 'rmcwhirterf@wikimedia.org', 'rmcwhirterf', 'xV0''E3Lr(SR@/', '1955-03-10', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (17, 'Odie Teideman', 'oteidemang@msu.edu', 'oteidemang', 'hM2*Ai_6', '2002-11-01', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (18, 'Thorin Barney', 'tbarneyh@twitter.com', 'tbarneyh', 'oY7"\DgH', '1999-11-02', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (19, 'Zilvia Buttle', 'zbuttlei@gnu.org', 'zbuttlei', 'hF3#+vOmXf%gYN+W', '1968-12-29', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (20, 'Linzy Cosford', 'lcosfordj@ibm.com', 'lcosfordj', 'hA8!gecS_/`', '1975-12-19', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (21, 'Kristen Cattell', 'kcattellk@slideshare.net', 'kcattellk', 'iQ5,`y}w%(', '1944-11-18', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (22, 'Gerick MacGlory', 'gmacgloryl@shutterfly.com', 'gmacgloryl', 'gO5<3tXvn`7?zl', '1974-12-13', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (23, 'Alec Medler', 'amedlerm@reuters.com', 'amedlerm', 'mO3{*ooR$8yLWg', '1936-05-20', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (24, 'Lance Cruddace', 'lcruddacen@fastcompany.com', 'lcruddacen', 'vU0%13%cFQ#', '1981-01-10', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (25, 'Heddi Wimpress', 'hwimpresso@qq.com', 'hwimpresso', 'rT9{6veu&i1b', '1987-11-23', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (26, 'Engelbert Tolefree', 'etolefreep@accuweather.com', 'etolefreep', 'rX5{pv|bQ', '1945-08-15', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (27, 'Demeter Josilevich', 'djosilevichq@fotki.com', 'djosilevichq', 'gB5/vSlAE', '1975-10-06', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (28, 'Cosme Callington', 'ccallingtonr@prnewswire.com', 'ccallingtonr', 'mJ1{EPf<j>sfL', '1973-08-25', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (29, 'Roley Ewols', 'rewolss@technorati.com', 'rewolss', 'mI6$6NoTDA~|0}ft', '2004-01-08', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (30, 'Chiquia Lovering', 'cloveringt@cnbc.com', 'cloveringt', 'yU7/6mmyOF,', '1991-01-23', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (31, 'Dierdre Jumont', 'djumontu@cbslocal.com', 'djumontu', 'yR2''dB`bHS)*z', '1976-04-17', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (32, 'Konrad Degue', 'kdeguev@amazonaws.com', 'kdeguev', 'yM3#B6coh6~A*!S', '1962-01-06', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (33, 'Sheilakathryn Filipov', 'sfilipovw@earthlink.net', 'sfilipovw', 'tT3+V"p@oItJ)n%', '1965-08-13', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (34, 'Tadio Highnam', 'thighnamx@answers.com', 'thighnamx', 'rW1@1<"+', '1962-04-26', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (35, 'Zerk Suddick', 'zsuddicky@wufoo.com', 'zsuddicky', 'qN0?rJakN', '1955-06-03', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (36, 'Berke Gosnay', 'bgosnayz@amazon.com', 'bgosnayz', 'tH5_\zns<8u?', '1948-02-23', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (37, 'Rutger Nenci', 'rnenci10@cargocollective.com', 'rnenci10', 'mW3.Q*/W8S\r', '1946-06-16', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (38, 'Aubry Billham', 'abillham11@google.com.hk', 'abillham11', 'eT0#SKL<B*+SzDLa', '1943-09-16', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (39, 'Reggie Cawsby', 'rcawsby12@weather.com', 'rcawsby12', 'uJ1{l0FMw.x\zwO', '2001-05-10', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (40, 'Benjy Kirkam', 'bkirkam13@livejournal.com', 'bkirkam13', 'tT8=1m?w8<P?I', '1965-08-03', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (41, 'Catlaina Vidineev', 'cvidineev14@comcast.net', 'cvidineev14', 'sJ4(_uw`uISk6R5k', '1954-02-04', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (42, 'Archie Huggett', 'ahuggett15@patch.com', 'ahuggett15', 'fP9"\TodM', '1944-04-26', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (43, 'Jacquenetta Phair', 'jphair16@hc360.com', 'jphair16', 'dK1.>%nW4I', '1936-04-20', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (44, 'Jolee Reynold', 'jreynold17@furl.net', 'jreynold17', 'zN8?/.Zf>}x<_c', '1981-10-01', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (45, 'Xaviera Hubbins', 'xhubbins18@photobucket.com', 'xhubbins18', 'tS1<Bu5VNUxv?X', '1968-05-31', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (46, 'Augie Souttar', 'asouttar19@reference.com', 'asouttar19', 'oA9($ZnvQzV', '1943-03-02', 'deactivated');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (47, 'Dimitry Stegell', 'dstegell1a@google.de', 'dstegell1a', 'qE2%2\wJ.xK', '1949-07-22', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (48, 'Adolph Cambling', 'acambling1b@twitpic.com', 'acambling1b', 'zJ9>NQ77KgogZ0)', '1972-05-21', 'active');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (49, 'Juieta Gallagher', 'jgallagher1c@dedecms.com', 'jgallagher1c', 'aB2|=MK3afXUdExo', '1989-02-18', 'payment pending');
insert into users (id, full_name, email, username, password, date_of_birth, status) values (50, 'Sunshine Dimitrie', 'sdimitrie1d@ucoz.com', 'sdimitrie1d', 'tX1%@YaAK', '1994-06-18', 'payment pending');

-- CARS DATA:
insert into cars (id, license_plate, brand, model, year, status) values (1, 'QOP732', 'Saab', '900', 1989, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (2, 'IJB243', 'BMW', '525', 2001, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (3, 'ECE539', 'Dodge', 'Caliber', 2011, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (4, 'ULT048', 'Jeep', 'Wrangler', 1995, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (5, 'SEC480', 'Chevrolet', 'Camaro', 2012, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (6, 'TAW787', 'Mazda', 'Protege', 1992, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (7, 'FAO755', 'Chrysler', 'PT Cruiser', 2003, 'rental ongoing');
insert into cars (id, license_plate, brand, model, year, status) values (8, 'MSM669', 'Ford', 'Econoline E350', 1999, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (9, 'HUW602', 'Mitsubishi', 'RVR', 1994, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (10, 'RCC192', 'Infiniti', 'I', 2001, 'rental ongoing');
insert into cars (id, license_plate, brand, model, year, status) values (11, 'PUB593', 'Land Rover', 'Defender 90', 1997, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (12, 'IAL342', 'Volvo', 'S60', 2008, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (13, 'ACB578', 'Chevrolet', 'S10', 2000, 'rental ongoing');
insert into cars (id, license_plate, brand, model, year, status) values (14, 'IYK747', 'BMW', 'X5', 2008, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (15, 'AVN000', 'Dodge', 'Ram 3500', 1999, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (16, 'IFE562', 'Audi', 'riolet', 1995, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (17, 'GZF868', 'Chevrolet', 'Corsica', 1995, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (18, 'BUP302', 'Audi', 'Q7', 2010, 'available');
insert into cars (id, license_plate, brand, model, year, status) values (19, 'TKY510', 'Chevrolet', 'Astro', 1995, 'rent ineligible');
insert into cars (id, license_plate, brand, model, year, status) values (20, 'WWO040', 'GMC', 'Jimmy', 2001, 'rental ongoing');

--RENTALS DATA:
INSERT INTO rentals (car_id, user_id, rental_date, status) VALUES (20, 5, '2026-08-15', 'ongoing');
INSERT INTO rentals (car_id, user_id, rental_date, status) VALUES (13, 28, '2026-08-15', 'ongoing');
INSERT INTO rentals (car_id, user_id, rental_date, status) VALUES (7, 42, '2026-08-14', 'ongoing');
INSERT INTO rentals (car_id, user_id, rental_date, status) VALUES (10, 3, '2026-08-11', 'ongoing');