SET search_path TO ejercicio;

-- SCHEMA:
CREATE TABLE users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(20) NOT NULL,
	email VARCHAR(30)
);

CREATE TABLE addresses (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	address VARCHAR(30) NOT NULL,
	user_id INTEGER REFERENCES users(id)
);

CREATE TABLE products (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_name VARCHAR(30) NOT NULL,
	price FLOAT NOT NULL,
	brand VARCHAR(30) NOT NULL,
	stock SMALLINT
);

CREATE TABLE bills (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER REFERENCES users(id),
	address_id INTEGER REFERENCES addresses(id),
	purchase_date DATE NOT NULL,
	status VARCHAR(15) NOT NULL, 
	delivery_date DATE
);

CREATE TABLE bill_products (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bill_id INTEGER REFERENCES bills(id),
	product_id INTEGER REFERENCES products(id),
	quantity SMALLINT NOT NULL
);

-- DATA DEFINITION:

-- users table:
INSERT INTO users (user_name, email)
    VALUES ('John Lennon', 'j.lennon@gmail.com');

INSERT INTO users (user_name, email)
    VALUES ('Jimi Hendrix', 'jimi_hendrix@hotmail.com');

INSERT INTO users (user_name, email)
	VALUES ('Kurt Cobain', 'kurt.cobain.1967@gmail.com');

-- addresses table:
INSERT INTO addresses (address, user_id)
	VALUES ('123 Main St', 1);

INSERT INTO addresses (address, user_id)
	VALUES ('456 Elm St', 2);

INSERT INTO addresses (address, user_id)
	VALUES ('4th Avenue', 2);

INSERT INTO addresses (address, user_id)
	VALUES ('789 Oak St', 3);

INSERT INTO addresses (address, user_id)
	VALUES ('464 Georgia St', 3);

-- products table:
INSERT INTO products (product_name, price, brand, stock)
    VALUES ('iPhone', 699.99, 'Apple', 12);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('iPad', 899.99, 'Apple', 5);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('MacBook Pro', 1999.99, 'Apple', 9);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('MacBook Air', 1299.99, 'Apple', 2);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('Stanmore IV Black', 429.99, 'Marshall', 10);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('Stanmore IV Cream', 429.99, 'Marshall', 17);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('Woburn III Black', 599.99, 'Marshall', 5);

INSERT INTO products (product_name, price, brand, stock)
    VALUES ('Woburn III Brown', 599.99, 'Marshall', 7);

INSERT INTO products (product_name, price, brand, stock)
	VALUES ('Monitor III A.N.C. Black', 379.99, 'Marshall', 1);

-- bills table:
INSERT INTO bills (user_id, address_id, purchase_date, status, delivery_date)
	VALUES (2, 3, '2026-07-29', 'Delivered', '2026-08-03');

INSERT INTO bills (user_id, address_id, purchase_date, status, delivery_date)
	VALUES (2, 2, '2026-07-30', 'Delivered', '2026-08-03');

INSERT INTO bills (user_id, address_id, purchase_date, status, delivery_date)
	VALUES (3, 5, '2026-08-02', 'Pending', NULL);

-- bill_products table:
INSERT INTO bill_products (bill_id, product_id, quantity)
	VALUES (1, 4, 1);

INSERT INTO bill_products (bill_id, product_id, quantity)
	VALUES (2, 6, 2);

INSERT INTO bill_products (bill_id, product_id, quantity)
	VALUES (3, 5, 1);
